---
name: New subscription
description: Create new subscription
title: New subscription request
labels:
  - new subscription
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Please fill in all the fields. We will not approve _corp_ subscriptions without a meeting.
  - type: input
    id: owner
    attributes:
      label: Owner
      description: Subscription owner
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Landing Zone
      description: Choose a landing zone
      options:
        - corp
        - online
        - sandbox
      default: 1
    validations:
      required: true
  - type: input
    id: cost_center
    attributes:
      label: Cost Center
      description: Enter your cost center
