---
name: New Subscription

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          echo $ISSUE_URL
