---
name: New Subscription

on:
  issues:
    types:
      - opened
      - labeled
      - edited

jobs:
  parse-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Issue
        id: parse
        uses: issue-ops/parser@v4.2.0
        with:
          body: ${{ github.event.issue.body }}
          issue-form-template: new-subscription.yml

      - name: Output the Parsed Issue
        id: output
        run: echo ${{ steps.parse.outputs.json }}
