---
name: New Subscription

on:
  issues:
    types:
      - labeled

jobs:
  parse-issue:
    runs-on: ubuntu-latest
    if: contains(github.event.labels.*.name, 'approved')
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          persist-credentials: false

      - name: Parse Issue
        id: parse
        uses: issue-ops/parser@v4.2.0
        with:
          body: ${{ github.event.issue.body }}
          issue-form-template: new-subscription.yml

      - name: Output the Parsed Issue
        id: output
        run: |
          echo "Owner: $OWNER"
          echo "Landing zone: $LANDING_ZONE"
          echo "Cost center: $COST_CENTER"

        env:
          OWNER: ${{ steps.parse.outputs.parsed_owner }}
          LANDING_ZONE: ${{ steps.parse.outputs.parsed_landing_zone }}
          COST_CENTER: ${{ steps.parse.outputs.parsed_cost_center }}